# Generated by Django 2.2.6 on 2019-11-29 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListValuesDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('list_DB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_elaboration_settings_list_DB', to='gproject.ListDB')),
            ],
        ),
        migrations.CreateModel(
            name='ElaborationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('mandatory', models.BooleanField()),
                ('range_from', models.CharField(max_length=100)),
                ('range_to', models.CharField(max_length=100)),
                ('list_DB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_elaboration_settings_list', to='gproject.ListDB')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_elaboration_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_elaboration', models.DateTimeField(blank=True, null=True)),
                ('document_input', models.FileField(blank=True, null=True, upload_to='static/documents/')),
                ('elaborated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_elaboration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
