# Generated by Django 2.2.6 on 2019-11-30 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborationsettings',
            name='option_value',
            field=models.CharField(choices=[('None', 'None'), ('List', 'List'), ('Range', 'Range')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='listvaluesdb',
            name='list_DB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_value', to='gproject.ListDB'),
        ),
    ]
