# Generated by Django 2.2.6 on 2019-11-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0002_auto_20191130_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaborationsettings',
            name='range_from',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='elaborationsettings',
            name='range_to',
            field=models.FloatField(blank=True),
        ),
    ]
