# Generated by Django 2.2.6 on 2019-11-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0003_auto_20191130_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaborationsettings',
            name='list_DB',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_elaboration_settings_list', to='gproject.ListDB'),
        ),
    ]
