# Generated by Django 2.2.6 on 2019-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0006_auto_20191130_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaborationsettings',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
