# Generated by Django 2.2.6 on 2019-12-02 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0007_auto_20191201_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elaborationsettings',
            name='list_DB',
        ),
        migrations.AddField(
            model_name='listdb',
            name='ElaborationSettings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ListDB_list', to='gproject.ElaborationSettings'),
        ),
    ]
