# Generated by Django 2.2.6 on 2019-12-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0008_auto_20191202_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listdb',
            name='ElaborationSettings',
        ),
        migrations.AddField(
            model_name='elaborationsettings',
            name='list_DB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_elaboration_settings_list', to='gproject.ListDB'),
        ),
    ]
