# Generated by Django 2.2.6 on 2019-12-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0011_auto_20191202_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaborationsettings',
            name='elaboration_settings_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elaboration_settings_group', to='gproject.ElaborationSettingsGroup'),
            preserve_default=False,
        ),
    ]
