# Generated by Django 2.2.6 on 2019-12-04 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gproject', '0012_elaborationsettings_elaboration_settings_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listdb',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_listDB', to=settings.AUTH_USER_MODEL),
        ),
    ]
